const DataPenerbangan = [
  [
    "Jakarta",
    "Jambi",
    "Lampung",
    "Kediri",
    "Ambon",
    "Aceh",
    "Maluku",
    "Pontianak",
    "Samarinda",
    "Bandung",
  ],
  [
    "Lampung",
    "Pontianak",
    "Jakarta",
    "Ambon",
    "kediri",
    "Lampung",
    "Jakarta",
    "Jambi",
    "Aceh",
    "Lampung",
  ],
  [
    "20 Oktober 2022",
    "19 Oktober 2022",
    "21 November 2022",
    "24 Juni 2022",
    "30 Oktober 2022",
    "25 Oktober 2022",
    "25 Oktober 2022",
    "25 Oktober 2022",
    "25 Oktober 2022",
    "25 Oktober 2022",
  ],
  [
    "Majapahit",
    "Majapahit",
    "Batik Air",
    "Lion Air",
    "Garuda Indonesia",
    "Lion Air",
    "Majapahit",
    "Batik Air",
    "Lion Air",
    "Majapahit",
  ],
];

export default DataPenerbangan;
